import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Sinan',
      email: 'sinan.sakic@gmail.com',
      password: bcrypt.hashSync('Sinana123'),
      isAdmin: false,
      image: '/images/sinan.jpeg'
    },
    {
      name: 'Milan',
      email: 'super.admin@gmail.com',
      password: bcrypt.hashSync('Dmdevelo123'),
      isAdmin: true,
      image: '/images/admin.jpg'
    },
    {
      name: 'Zoran Drazic',
      email: 'zokac.pokac@gmail.com',
      password: bcrypt.hashSync('Z@kula03'),
      isAdmin: false,
      image: '/images/lenjivac.jpg',
      birthday: '03.10.1988',
      address: 'Vase Stajica 16',
      phone: '381644356988',
      country: 'Serbia',
      city: 'Sremska Mitrovica',
      postalcode: '22000',
      company: '',
      vatNumber: null,
      newsletter: 'newsletter',
    }
  ],
  products: [
    {
      title: "AMD Ryzen 53500",
      images: [{image: "/images/amd_desktop/amd-desktop-ryzen.png"}, {image: "/images/amd_desktop/amd_ryzen.png"}, {image: "/images/amd_desktop/desktopAvatar.png"}, {image: "/images/amd_desktop/desktop_ryzen.png"}],
      shortDescription: "Ryzen 5 | 3.6 GHz | Chipset B450 | RAM 16 GB | SSD 500 GB | Nvidia RTX 3050 8GB GDDR6",
      description: "Processor type: Ryzen 5 Processor model: Ryzen 3500, Processor clock speed: 3.6 GHz, Motherboard chipset: B450, Memory: 16 GB, Hard disk type: SSD Hard disk capacity: 500 GB, Graphics card: Nvidia, Graphics card model: NVD RTX 3050, Graphics card memory: 8GB GDDR6",
      rating: 4,
      price: 1120,
      oldPrice: 1200,
      slug: "amd-ryzen-53500",
      category: "Desktop computers",
      categoryUrl: "desktop-computers",
      subCategory: "AMD Computers",
      subCategoryUrl: "AMD-Computers",
      brand: "AMD",
      brandImg: "/logo/AMD-logo.png",
      reviews: 3,
      inStock: 10,
      inWidget: "hero"
    },
    {
      title: "AMD Acer Aspire",
      images: [{image: "/images/acer_desktop/acer_desk.png"}, {image: "/images/acer_desktop/amd-acer-desktop.jpg"}, {image: "/images/acer_desktop/acer_desk_full-set"}, {image: "/images/acer_desktop/acer_desktop.png"}, {image: "/images/acer_desktop/amd-acer-desktop.png"}],
      shortDescription: "Ryzen 5 | 3.6 GHz | Chipset B450 | RAM 16 GB | SSD 500 GB | Nvidia RTX 3050 8GB GDDR6",
      description: "Processor type: Ryzen 5 Processor model: Ryzen 3500, Processor clock speed: 3.6 GHz, Motherboard chipset: B450, Memory: 16 GB, Hard disk type: SSD Hard disk capacity: 500 GB, Graphics card: Nvidia, Graphics card model: NVD RTX 3050, Graphics card memory: 8GB GDDR6",
      rating: 4,
      price: 990,
      oldPrice: 1090,
      slug: "amd-acer-aspire",
      category: "Desktop computers",
      categoryUrl: "desktop-computers",
      subCategory: "AMD Computers",
      subCategoryUrl: "AMD-Computers",
      brand: "AMD",
      brandImg: "/logo/AMD-logo.png",
      reviews: 5,
      inStock: 10,
      inWidget: "top-product",
    },
    {
      title: "AMD Dell Desktop",
      images: [{image: "/images/dell_desktop/amd-dell-desktop.png"}, {image: "/images/dell_desktop/dell_desktop.png"}],
      shortDescription: "Ryzen 5 | 3.6 GHz | Chipset B450 | RAM 16 GB | SSD 500 GB | Nvidia RTX 3050 8GB GDDR6",
      description: "Processor type: Ryzen 5 Processor model: Ryzen 3500, Processor clock speed: 3.6 GHz, Motherboard chipset: B450, Memory: 16 GB, Hard disk type: SSD Hard disk capacity: 500 GB, Graphics card: Nvidia, Graphics card model: NVD RTX 3050, Graphics card memory: 8GB GDDR6",
      rating: 4,
      price: 1800,
      oldPrice: 1910,
      slug: "amd-dell-desktop",
      category: "Desktop computers",
      categoryUrl: "desktop-computers",
      subCategory: "AMD Computers",
      subCategoryUrl: "AMD-Computers",
      brand: "Dell",
      brandImg: "/logo/dell-logo.png",
      reviews: 3,
      inStock: 10,
      inWidget: "hero"
    },
    {
      title: "Dell PRO",
      images: [{image: "/images/dell_desktop/dell_desktop.png"}],
      shortDescription: "Ryzen 5 | 3.6 GHz | Chipset B450 | RAM 16 GB | SSD 500 GB | Nvidia RTX 3050 8GB GDDR6",
      description: "Processor type: Ryzen 5 Processor model: Ryzen 3500, Processor clock speed: 3.6 GHz, Motherboard chipset: B450, Memory: 16 GB, Hard disk type: SSD Hard disk capacity: 500 GB, Graphics card: Nvidia, Graphics card model: NVD RTX 3050, Graphics card memory: 8GB GDDR6",
      rating: 4,
      price: 2190,
      oldPrice: 2500,
      slug: "dell-pro-desktop",
      category: "Desktop computers",
      categoryUrl: "desktop-computers",
      subCategory: "Dell Computers",
      subCategoryUrl: "Dell-Computers",
      brand: "Dell",
      brandImg: "/logo/dell-logo.png",
      reviews: 3,
      inStock: 10,
      inWidget: "best-seller"
    },
    {
      title: "Dell business",
      images: [{image: "/images/dell_desktop/amd-dell-desktop.png"}],
      shortDescription: "Ryzen 5 | 3.6 GHz | Chipset B450 | RAM 16 GB | SSD 500 GB | Nvidia RTX 3050 8GB GDDR6",
      description: "Processor type: Ryzen 5 Processor model: Ryzen 3500, Processor clock speed: 3.6 GHz, Motherboard chipset: B450, Memory: 16 GB, Hard disk type: SSD Hard disk capacity: 500 GB, Graphics card: Nvidia, Graphics card model: NVD RTX 3050, Graphics card memory: 8GB GDDR6",
      rating: 4,
      price: 2100,
      oldPrice: 2150,
      slug: "dell-business",
      category: "Desktop computers",
      categoryUrl: "desktop-computers",
      subCategory: "Dell Computers",
      subCategoryUrl: "Dell-Computers",
      brand: "Dell",
      brandImg: "/logo/dell-logo.png",
      reviews: 3,
      inStock: 10,
      inWidget: "top-product"
    },
    {
      title: "HP server",
      images: [{image: "/images/hp_desktop/servers-hewlett-packard.png"}, {image: "/images/hp_desktop/servers-hp.png"}],
      shortDescription: "Ryzen 5 | 3.6 GHz | Chipset B450 | RAM 16 GB | SSD 500 GB | Nvidia RTX 3050 8GB GDDR6",
      description: "Processor type: Ryzen 5 Processor model: Ryzen 3500, Processor clock speed: 3.6 GHz, Motherboard chipset: B450, Memory: 16 GB, Hard disk type: SSD Hard disk capacity: 500 GB, Graphics card: Nvidia, Graphics card model: NVD RTX 3050, Graphics card memory: 8GB GDDR6",
      rating: 3,
      price: 1980,
      oldPrice: 2050,
      slug: "hp-server-computer",
      category: "Desktop computers",
      categoryUrl: "desktop-computers",
      subCategory: "HP Computers",
      subCategoryUrl: "HP-Computers",
      brand: "HP",
      brandImg: "/logo/hp-logo.png",
      reviews: 3,
      inStock: 10,
      inWidget: "top-product"
    },
    {
      title: "HP home racunar",
      images: [{image: "/images/hp_desktop/hp-desktop.png"}, {image: "/images/hp_desktop/hp-pavilion.png"}],
      shortDescription: "Ryzen 5 | 3.6 GHz | Chipset B450 | RAM 16 GB | SSD 500 GB | Nvidia RTX 3050 8GB GDDR6",
      description: "Processor type: Ryzen 5 Processor model: Ryzen 3500, Processor clock speed: 3.6 GHz, Motherboard chipset: B450, Memory: 16 GB, Hard disk type: SSD Hard disk capacity: 500 GB, Graphics card: Nvidia, Graphics card model: NVD RTX 3050, Graphics card memory: 8GB GDDR6",
      rating: 3,
      price: 1200,
      oldPrice: 1350,
      slug: "hp-home-desktop",
      category: "Desktop computers",
      categoryUrl: "desktop-computers",
      subCategory: "HP Computers",
      subCategoryUrl: "HP-Computers",
      brand: "HP",
      brandImg: "/logo/hp-logo.png",
      reviews: 3,
      inStock: 10,
      inWidget: "top-product"
    },
    {
      title: "Acer laptop",
      images: [{image: "/images/acer_laptop/acer-laptop.png"}, {image: "/images/acer_laptop/acer-lap.png"}, {image: "/images/acer_laptop/acer-laptop_green.png"}],
      shortDescription: "Ryzen 5 | 3.6 GHz | Chipset B450 | RAM 16 GB | SSD 500 GB | Nvidia RTX 3050 8GB GDDR6",
      description: "Processor type: Ryzen 5 Processor model: Ryzen 3500, Processor clock speed: 3.6 GHz, Motherboard chipset: B450, Memory: 16 GB, Hard disk type: SSD Hard disk capacity: 500 GB, Graphics card: Nvidia, Graphics card model: NVD RTX 3050, Graphics card memory: 8GB GDDR6",
      rating: 4,
      price: 630,
      oldPrice: 690,
      slug: "acer-notebook",
      category: "Laptop computers",
      categoryUrl: "laptops",
      subCategory: "Acer Laptops",
      subCategoryUrl: "Acer-Laptops",
      brand: "Acer",
      brandImg: "/logo/acer-logo.png",
      reviews: 3,
      inStock: 10,
      inWidget: "best-seller"
    },
    {
      title: "Lenovo laptop",
      images: [{image: "/images/lenovo_laptop/lenovo_laptop_two.png"}, {image: "/images/lenovo_laptop/lenovo_laptop_one.png"}, {image: "/images/lenovo_laptop/lenovo-laptop.png"}],
      shortDescription: "Ryzen 5 | 3.6 GHz | Chipset B450 | RAM 16 GB | SSD 500 GB | Nvidia RTX 3050 8GB GDDR6",
      description: "Processor type: Ryzen 5 Processor model: Ryzen 3500, Processor clock speed: 3.6 GHz, Motherboard chipset: B450, Memory: 16 GB, Hard disk type: SSD Hard disk capacity: 500 GB, Graphics card: Nvidia, Graphics card model: NVD RTX 3050, Graphics card memory: 8GB GDDR6",
      rating: 2,
      price: 650,
      oldPrice: 699,
      slug: "lenovo-laptop",
      category: "Laptop computers",
      categoryUrl: "laptops",
      subCategory: "Lenovo Laptops",
      subCategoryUrl: "Lenovo-Laptops",
      brand: "Lenovo",
      brandImg: "/logo/Lenovo-Logo.png",
      reviews: 3,
      inStock: 10,
      inWidget: "hero"
    },
    {
      title: "Toshiba Satellite",
      images: [{image: "/images/toshiba_laptop/toshiba.png"}, {image: "/images/toshiba_laptop/toshiba-expands.png"}, {image: "/images/toshiba_laptop/toshiba_satellite.png"}],
      shortDescription: "Ryzen 5 | 3.6 GHz | Chipset B450 | RAM 16 GB | SSD 500 GB | Nvidia RTX 3050 8GB GDDR6",
      description: "Processor type: Ryzen 5 Processor model: Ryzen 3500, Processor clock speed: 3.6 GHz, Motherboard chipset: B450, Memory: 16 GB, Hard disk type: SSD Hard disk capacity: 500 GB, Graphics card: Nvidia, Graphics card model: NVD RTX 3050, Graphics card memory: 8GB GDDR6",
      rating: 4,
      price: 880,
      oldPrice: 920,
      slug: "toshiba-satellite",
      category: "Laptop computers",
      categoryUrl: "laptops",
      subCategory: "Toshiba Laptops",
      subCategoryUrl: "Toshiba-Laptops",
      brand: "Toshiba",
      brandImg: "/logo/Toshiba-Logo.png",
      reviews: 10,
      inStock: 0,
      inWidget: "hero"
    },
    {
      title: "Xiaomi Redmi Note 9",
      images: [{image: "/images/xiaomi_mobile/Redmi-Note-9-1pro.png"}, {image: "/images/xiaomi_mobile/xiaomi_5G.webp"}, {image: "/images/xiaomi_mobile/xiaomi_5G_front.webp"}],
      shortDescription: "Ryzen 5 | 3.6 GHz | Chipset B450 | RAM 16 GB | SSD 500 GB | Nvidia RTX 3050 8GB GDDR6",
      description: "Processor type: Ryzen 5 Processor model: Ryzen 3500, Processor clock speed: 3.6 GHz, Motherboard chipset: B450, Memory: 16 GB, Hard disk type: SSD Hard disk capacity: 500 GB, Graphics card: Nvidia, Graphics card model: NVD RTX 3050, Graphics card memory: 8GB GDDR6",
      rating: 4,
      price: 900,
      oldPrice: 980,
      slug: "xiaomi-redmi-note-9",
      category: "Smartphones",
      categoryUrl: "smartphones",
      subCategory: "Xiaomi Smartphones",
      subCategoryUrl: "Xiaomi-Smartphones",
      brand: "Xiaomi",
      brandImg: "/logo/Xiaomi_logo.png",
      reviews: 3,
      inStock: 10,
      inWidget: "hero"
    },
    {
      title: "Xiaomi 10",
      images: [{image: "/images/xiaomi_mobile/xiaomi_5G.webp"}, {image: "/images/xiaomi_mobile/xiaomi_5G_front.webp"}],
      shortDescription: "Ryzen 5 | 3.6 GHz | Chipset B450 | RAM 16 GB | SSD 500 GB | Nvidia RTX 3050 8GB GDDR6",
      description: "Processor type: Ryzen 5 Processor model: Ryzen 3500, Processor clock speed: 3.6 GHz, Motherboard chipset: B450, Memory: 16 GB, Hard disk type: SSD Hard disk capacity: 500 GB, Graphics card: Nvidia, Graphics card model: NVD RTX 3050, Graphics card memory: 8GB GDDR6",
      rating: 4,
      price: 980,
      oldPrice: 1020,
      slug: "xiaomi-10-phone",
      category: "Smartphones",
      categoryUrl: "smartphones",
      subCategory: "Xiaomi Smartphones",
      subCategoryUrl: "Xiaomi-Smartphones",
      brand: "Xiaomi",
      brandImg: "/logo/Xiaomi_logo.png",
      reviews: 3,
      inStock: 10,
      inWidget: "top-product"
    },
    {
      title: "Nokia Seven",
      images: [{image: "/images/nokia_mobile/nokia-smartphone.png"}, {image: "/images/nokia_mobile/nokia_quad.webp"}, {image: "/images/nokia_mobile/nokia_quad_front.webp"}, {image: "/images/nokia_mobile/nokia_quad_back.webp"}],
      shortDescription: "Ryzen 5 | 3.6 GHz | Chipset B450 | RAM 16 GB | SSD 500 GB | Nvidia RTX 3050 8GB GDDR6",
      description: "Processor type: Ryzen 5 Processor model: Ryzen 3500, Processor clock speed: 3.6 GHz, Motherboard chipset: B450, Memory: 16 GB, Hard disk type: SSD Hard disk capacity: 500 GB, Graphics card: Nvidia, Graphics card model: NVD RTX 3050, Graphics card memory: 8GB GDDR6",
      rating: 4,
      price: 789,
      oldPrice: 880,
      slug: "nokia-seven-mobile",
      category: "Smartphones",
      categoryUrl: "smartphones",
      subCategory: "Nokia Smartphones",
      subCategoryUrl: "Nokia-Smartphones",
      brand: "Nokia",
      brandImg: "/logo/nokia-logo.png",
      reviews: 3,
      inStock: 10,
      inWidget: "hero"
    },
    {
      title: "Nokia Spring",
      images: [{image: "/images/nokia_mobile/nokia_quad_back.webp"}, {image: "/images/nokia_mobile/nokia_quad_front.webp"}],
      shortDescription: "Ryzen 5 | 3.6 GHz | Chipset B450 | RAM 16 GB | SSD 500 GB | Nvidia RTX 3050 8GB GDDR6",
      description: "Processor type: Ryzen 5 Processor model: Ryzen 3500, Processor clock speed: 3.6 GHz, Motherboard chipset: B450, Memory: 16 GB, Hard disk type: SSD Hard disk capacity: 500 GB, Graphics card: Nvidia, Graphics card model: NVD RTX 3050, Graphics card memory: 8GB GDDR6",
      rating: 4,
      price: 755,
      oldPrice: 850,
      slug: "nokia-spring-mobile",
      category: "Smartphones",
      categoryUrl: "smartphones",
      subCategory: "Nokia Smartphones",
      subCategoryUrl: "Nokia-Smartphones",
      brand: "Nokia",
      brandImg: "/logo/nokia-logo.png",
      reviews: 3,
      inStock: 10,
      inWidget: "top-product"
    },
    {
      title: "Huawei 14x Elite",
      images: [{image: "/images/huawei_mobile/huawei.png"}, {image: "/images/huawei_mobile/huawei_smart.png"}, {image: "/images/huawei_mobile/huawei_smart_back-front.webp"}],
      shortDescription: "Ryzen 5 | 3.6 GHz | Chipset B450 | RAM 16 GB | SSD 500 GB | Nvidia RTX 3050 8GB GDDR6",
      description: "Processor type: Ryzen 5 Processor model: Ryzen 3500, Processor clock speed: 3.6 GHz, Motherboard chipset: B450, Memory: 16 GB, Hard disk type: SSD Hard disk capacity: 500 GB, Graphics card: Nvidia, Graphics card model: NVD RTX 3050, Graphics card memory: 8GB GDDR6",
      rating: 3,
      price: 980,
      oldPrice: 1025,
      slug: "huawei-s14x-elite",
      category: "Smartphones",
      categoryUrl: "smartphones",
      subCategory: "Huawei Smartphones",
      subCategoryUrl: "Huawei-Smartphones",
      brand: "Huawei",
      brandImg: "/logo/huawei-logo.png",
      reviews: 3,
      inStock: 10,
      inWidget: "hero"
    }
  ]
}

export default data;